// <auto-generated />
using CoreWebAngularApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreWebAngularApplication.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200602163419_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreWebAngularApplication.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin@gmail.com",
                            Password = "12345",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Login = "qwerty@gmail.com",
                            Password = "55555",
                            Role = "user"
                        },
                        new
                        {
                            Id = 3,
                            Login = "qwerty2@gmail.com",
                            Password = "77777",
                            Role = "user"
                        });
                });

            modelBuilder.Entity("CoreWebAngularApplication.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Apple",
                            Name = "iPhone X",
                            Price = 79900
                        },
                        new
                        {
                            Id = 2,
                            Company = "Samsung",
                            Name = "Galaxy S8",
                            Price = 49900
                        },
                        new
                        {
                            Id = 3,
                            Company = "Google",
                            Name = "Pixel 2",
                            Price = 52900
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
